// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uixogobytjepprqjvvtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpeG9nb2J5dGplcHBycWp2dnR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MzU4MTIsImV4cCI6MjA3MDExMTgxMn0.nZuUZwYlLLA9XIYSZgkFOTPPB3KxO5p2_RJoGJIF2sY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});